name: zarb_navard_game
description: "ضرب نورد"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flame: ^1.19.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  
  flutter_launcher_icons: ^0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  animations: ^2.0.0
  flip_card: ^0.7.0
  shared_preferences: ^2.0.6
  adaptive_theme: ^3.6.0
  pathfinding: ^3.0.1
  provider: ^6.0.2
  flutter_swipe_detector: ^2.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  build_runner: ^2.1.7
  hive_generator: ^2.0.1
  flutter_riverpod: ^1.0.4
  flame_audio: ^1.2.0


  uuid: ^3.0.6


  json_annotation: ^4.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/Home_page_assets/
    - assets/splash_screen_assets/
    - assets/LeaderBoard_assets/
    - assets/LeaderBoard_assets/character3.png
    - assets/images/
    - assets/logo.png

  fonts:
    - family: IranSansX
      fonts:
        - asset: assets/Fonts/IRANSansX-Black.ttf
          weight: 900
        - asset: assets/Fonts/IRANSansX-Bold.ttf
          weight: 700
        - asset: assets/Fonts/IRANSansX-DemiBold.ttf
          weight: 600
        - asset: assets/Fonts/IRANSansX-ExtraBlack.ttf
          weight: 800
        - asset: assets/Fonts/IRANSansX-ExtraBold.ttf
          weight: 700
        - asset: assets/Fonts/IRANSansX-Heavy.ttf
          weight: 800
        - asset: assets/Fonts/IRANSansX-Light.ttf
          weight: 300
        - asset: assets/Fonts/IRANSansX-Medium.ttf
          weight: 500
        - asset: assets/Fonts/IRANSansX-Regular.ttf
          weight: 400
        - asset: assets/Fonts/IRANSansX-Thin.ttf
          weight: 100
        - asset: assets/Fonts/IRANSansX-UltraLight.ttf
          weight: 200

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  
  
