name: zarb_navard_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flame: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  animations: ^2.0.0
  flip_card: ^0.6.0
  shared_preferences: ^2.0.6
  adaptive_theme: ^2.2.0  # Add this

flutter:
  uses-material-design: true

  assets:
    - assets/Home_page_assets/
    - assets/splash_screen_assets/
    - assets/LeaderBoard_assets/
    - assets/LeaderBoard_assets/character3.png

  fonts:
    - family: IranSansX
      fonts:
        - asset: assets/Fonts/IRANSansX-Black.ttf
          weight: 900
        - asset: assets/Fonts/IRANSansX-Bold.ttf
          weight: 700
        - asset: assets/Fonts/IRANSansX-DemiBold.ttf
          weight: 600
        - asset: assets/Fonts/IRANSansX-ExtraBlack.ttf
          weight: 800
        - asset: assets/Fonts/IRANSansX-ExtraBold.ttf
          weight: 700
        - asset: assets/Fonts/IRANSansX-Heavy.ttf
          weight: 800
        - asset: assets/Fonts/IRANSansX-Light.ttf
          weight: 300
        - asset: assets/Fonts/IRANSansX-Medium.ttf
          weight: 500
        - asset: assets/Fonts/IRANSansX-Regular.ttf
          weight: 400
        - asset: assets/Fonts/IRANSansX-Thin.ttf
          weight: 100
        - asset: assets/Fonts/IRANSansX-UltraLight.ttf
          weight: 200